import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/layouts/header";
import Footer from "./components/layouts/footer";
import AuthenticatedHeader from "./components/layouts/authenticated_header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Conduit Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <title>Conduit</title>
        <link
          href="//code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css"
          rel="stylesheet"
          type="text/css"
        />
        <link
          href="//fonts.googleapis.com/css?family=Titillium+Web:700|Source+Serif+Pro:400,700|Merriweather+Sans:400,700|Source+Sans+Pro:400,300,600,700,300italic,400italic,600italic,700italic"
          rel="stylesheet"
          type="text/css"
        />
        <link rel="stylesheet" href="//demo.productionready.io/main.css" />
      </head>
      <body className={inter.className}>
        <AuthenticatedHeader />
        {/* <Header /> */}
        {children}
        <Footer />
      </body>
    </html>
  );
}
